
[server]
	service_name="api-gateway"
	port = 10000

[log]
	level="debug"
	logpath="logs"
	rotate="hour"

[[redis]]
	server_name="school.api.redis"
	addr="127.0.0.1:6379"
#	password="fsgit_2020"
	max_idle=1000
	max_active=1000
	idle_timeout=1000
	connect_timeout=300
	read_timeout=100
	write_timeout=100
	database=0
	slow_time = 200


[[database]]
	name="school.api.db"
	master = "root:root@tcp(127.0.0.1:3306)/school?charset=utf8&parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci"
	slaves = ["root:root@tcp(127.0.0.1:3306)/school?charset=utf8&parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci"]

