
// Generated by the inits tool.  DO NOT EDIT!
package http
import (
	httpserver "github.com/lfxnxf/frame/logic/inits/http/server"
)


func initRoute(s httpserver.Server) {

	s.ANY("/ping", ping)

	s.GET("/hello", func(c *httpserver.Context) {
		c.JSON(struct {
			Message string `json:"message"`
		}{
			Message: "hello trip, 你好, 校车通",
		}, nil)
	})

}

